[functions]
  node_bundler = "esbuild"
  included_files = ["tina/database", "tina/generated/*" ]

[[redirects]]
  from = "/api/tina/*"
  to = "/.netlify/functions/tina"
  status = 200
  force = true

[dev]
  command = "npm run dev"
  publish = "_site"